services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: pass
      KC_DB_URL: jdbc:postgresql://thesis_postgres:5432/thesis
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8082:8080"
    command: -v start-dev --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data/import

  postgres:
    image: postgres:latest
    container_name: thesis_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: thesis
    ports:
      - "5432:5432"